### ISSUE TITLE
An imported Pack with two Concepts differing only in case crashes the app on every launch

### ISSUE THREAD

**Issue by Ooolaa** [Ooolaa/TechPulse#22]
## What happens

`PackValidator` rejects duplicate Concept names **case-sensitively**, but `PackInstaller` resolves them **case-insensitively**. A Pack containing both `"RAG"` and `"rag"` passes validation, and can then collapse to one Concept — leaving `InstalledPack.conceptNames` holding the same name twice, which traps `Dictionary(uniqueKeysWithValues:)`.

The result is an unrecoverable crash loop triggered by an imported file.

## The two halves that disagree

- `TechPulse/Services/PackFile.swift:157` — `var names: Set<String> = []` / `names.insert(concept.name)`. Exact-name comparison, so `"RAG"` and `"rag"` are two distinct names and validation passes.
- `TechPulse/Services/PackInstaller.swift:181` — resolves each Pack Concept as `byExactName[name] ?? byLowerName[name.lowercased()]`.

## Precondition

The store must already hold a Concept whose name matches both under lowercasing. That is reachable through ordinary use: `KnowledgeEngine.findOrCreateConcept` dedupes on `name.lowercased()` but stores whatever name the article analysis produced, so a Concept named `rag` can exist before any Pack is imported.

Given a store with `rag`, and an imported Pack declaring `"RAG"` and `"rag"`:

- `"RAG"` → exact miss → `byLowerName["rag"]` → the `rag` row
- `"rag"` → exact hit → the same `rag` row
- `record.conceptNames == ["rag", "rag"]`

## Where it traps

`ActivePack.topologicalOrder` (`TechPulse/Services/PackInstaller.swift:111` and `:116`) builds two dictionaries straight from `conceptNames`:

```swift
let rank = Dictionary(uniqueKeysWithValues: conceptNames.enumerated().map { ($1, $0) })
var remaining = Dictionary(uniqueKeysWithValues: conceptNames.map { ($0, 0) })
```

Both trap on a duplicate key. `pathOrder` is reached from `KnowledgePathEngine.nextDot`, so the trap fires inside the importer and then on every launch that renders the next-dot banner.

## Suggested fix

Two independent guards, both worth having:

1. `PackValidator` should reject duplicates on `name.lowercased()`, so the Pack never validates. This is the real fix — it keeps a bad file out.
2. `topologicalOrder` should tolerate duplicates (`uniquingKeysWith:`), so a name collision degrades the ordering rather than killing the process.

## Provenance

Found by `/code-review` over `main...pack-file-format`. Pre-existing: the import path landed in #7, the resolution logic in #4. Not introduced by #8/#9/#10.

**Comment by Ooolaa** [comment]
> *This was generated by AI during triage.*

## Verification

Reproduced deterministically over an in-memory store. All three steps confirmed:

1. `PackValidator.validate` **accepts** a Pack declaring both `"RAG"` and `"rag"` — so the bug is reachable from an imported file.
2. Installing that Pack over a store already holding a Concept named `rag` produces `conceptNames == ["rag", "rag"]` against a single Concept row.
3. Asking the active Pack for its path order then traps:

```
Swift/NativeDictionary.swift:792: Fatal error: Duplicate values for key: 'rag'
Restarting after unexpected exit, crash, or test timeout
```

The test runner restarted and crashed again on the same input — the crash loop, observed rather than inferred.

**Also found during verification:** exporting the active Pack is corrupted by the same duplicate. The export builds its concept list from the stored concept names, so it emits the collapsed Concept twice and produces a Pack file that fails validation on round-trip.

**Checked and safe** — do not "fix" these: the acyclicity check builds a dictionary keyed by Pack-file concept name, but it runs only after the uniqueness check inside validation, so it cannot see a duplicate. The graph view's dictionaries are keyed by array index and by `Concept.name`, which is unique in the store.

## Agent Brief

**Category:** bug
**Summary:** A Pack whose Concept names differ only by case can collapse to a single Concept, leaving duplicate entries in the installed Pack's concept list, which traps on the next read.

**Current behavior:**
Pack validation treats Concept names as distinct if they differ in any way, including case. Installation resolves each of the Pack's Concepts against existing Concepts case-insensitively, so several Pack Concepts can resolve to the same stored Concept. The installed Pack record then lists that Concept's name once per Pack entry that resolved to it.

Deriving the reading order from that record builds dictionaries keyed by concept name and traps on the duplicate. The order is read whenever a next recommendation is produced, which happens inside the importer and then on every launch that renders the recommendation, so the app cannot start. The trigger is a file the reader imported, so no code change on their part recovers it.

**Desired behavior:**
A Pack whose Concept names collide case-insensitively is rejected at validation with the existing duplicate-concept error, naming the offending Concept. Nothing is written to the store.

Independently, deriving a reading order from an installed Pack must not trap if its concept list somehow contains a repeat. A repeated name should be treated as the one Concept it refers to, and the resulting order should list it once.

**Key interfaces:**
- `PackValidator.validate(_:)` — its Concept-name uniqueness check should compare names case-insensitively, throwing the existing `PackValidationError.duplicateConcept` with the name as authored.
- `ActivePack.pathOrder(dependencies:)` and the topological ordering behind it — must tolerate a repeated concept name rather than trapping. The returned order should contain each distinct name exactly once.
- `PackInstaller.install(_:origin:context:)` — the concept-name list and the side-quest list it writes to the installed Pack record should not contain a name twice, even when several Pack Concepts resolve to one stored Concept.

**Acceptance criteria:**
- [ ] Validating a Pack containing two Concepts whose names differ only by case throws `duplicateConcept`; a Pack with genuinely distinct names still validates.
- [ ] Installing such a Pack throws and leaves no Concept, no Dependency and no installed-Pack record behind.
- [ ] Given an installed Pack record whose concept list contains a repeated name, asking for the path order returns without trapping, and the result contains that name once.
- [ ] The path order still covers every distinct Concept in the Pack exactly once, and still follows authored Stages ahead of dependency order (ADR-0004).
- [ ] Exporting an active Pack produces a Pack file that passes validation, including after an install that resolved two Pack Concepts to one stored Concept.
- [ ] The existing Pack installer, Pack file and pack-driven path suites still pass.

**Out of scope:**
- Changing how installation matches Pack Concepts to existing Concepts. The case-insensitive match is deliberate — it is what lets a Concept a reader's own reading created under different casing keep its Mastery and history when a Pack later names it. Do not make that match case-sensitive.
- Renaming or merging Concepts already in the store.
- The other `Dictionary(uniqueKeysWithValues:)` in feed syncing — that is a separate defect, tracked as #23.
- Any change to the Pack file format or its version.

**Comment by Ooolaa** [comment]
Fixed in `364c612` on `pack-file-format`.

The two halves disagreed about identity: `PackValidator` rejected duplicate names on the exact string, `PackInstaller` resolved them case-insensitively. "RAG" and "rag" passed validation, landed on one stored row, and the record named it twice — then `topologicalOrder`'s `Dictionary(uniqueKeysWithValues:)` trapped on the repeat behind the next-dot banner, on every launch.

Both ends are now guarded, because they cover different populations: the validator folds case so no such file gets in from here, and `namedOnce` normalises a stored record on the way out, so a record already written by an earlier build degrades rather than crashing. Reading it there rather than at the trap site also fixes the pack library's concept count, the side-quest total, and `exportActivePack` emitting a file the new validator would refuse.

Case-insensitive *resolution* is unchanged and deliberate — a Concept created as `rag` by the reader's own reading keeps its name, Mastery and history when a Pack calls it `RAG`.

206 unit tests pass, three of them new.
