### ISSUE TITLE
Two Sources sharing a name crash the first sync that has nothing cached for either

### ISSUE THREAD

**Issue by Ooolaa** [Ooolaa/TechPulse#23]
## What happens

`FeedSyncService.syncAll` builds its new-source bootstrap map keyed by Source **name**:

```swift
// TechPulse/Services/FeedSyncService.swift:66
var bootstrap: [String: Int] = Dictionary(
    uniqueKeysWithValues: sources
        .filter { !cachedSourceNames.contains($0.name) }
        .map { ($0.name, 5) }
)
```

Source names are not unique. `SeedData` and `PackSourceOffer` both dedupe on **URL**, never on name — so a Pack that suggests a Source whose name matches one the reader already subscribes to under a different URL produces two rows with the same name. If neither has anything cached, both survive the filter and `Dictionary(uniqueKeysWithValues:)` traps.

## When it is reachable

Both Sources must have nothing cached at the moment of the sync. That happens on a fresh install, and again after `FeedSyncService`'s 60-day pruning clears a Source's articles.

## Suggested fix

Key the map by URL, which is what the rest of the app treats as a Source's identity — or at minimum use `uniquingKeysWith:`.

## Provenance

Found by `/code-review` over `main...pack-file-format`. Pre-existing, and not introduced by #8/#9/#10.

**Comment by Ooolaa** [comment]
> *This was generated by AI during triage.*

## Verification

**Confirmed.** Constructing two enabled Sources with the same name and no cached articles, then running a sync:

```
Swift/NativeDictionary.swift:792: Fatal error: Duplicate values for key: 'arXiv cs.AI'
```

The trap is on an unconditional path — the bootstrap map is built from the enabled Sources after the fetch completes, so it fires whether or not any feed responded.

## Reachability — narrower than first reported

- Requires an **imported** Pack suggesting a Source whose name matches an existing subscription under a **different URL**. `PackSourceOffer` matches suggestions by URL only — deliberately, and documented as such — so a name collision passes through and is offered.
- The two built-in Packs were checked against the seeded defaults: **no name collisions**. Not reachable out of the box.
- Both Sources must have nothing cached under that name. That is the window between subscribing and the first successful sync, or after 60-day pruning clears that name. If the pre-existing Source already has cached articles, its name is in the cached set, both are filtered out, and nothing traps.
- Self-sustaining once hit: the sync crashes, so neither Source can acquire the articles that would close the window. The reader has to disable one Source in Settings to recover.

## Agent Brief

**Category:** bug
**Summary:** Syncing traps when two enabled Sources share a name and neither has cached articles.

**Current behavior:**
Feed syncing gives Sources with nothing cached a small article allowance outside the daily intake cap, so a newly added Source is not starved on a day whose intake is already spent. That allowance is held in a dictionary keyed by Source **name**, built with a duplicate-key-intolerant initializer.

Source names are not unique. Subscription is deduplicated by URL everywhere it happens, never by name, so two Sources can share a name under different URLs. When both lack cached articles, both are entered into that map and the process traps. Because syncing is how a Source acquires articles, the condition cannot clear itself.

**Desired behavior:**
Syncing completes normally when two enabled Sources share a name. Colliding Sources may share a single bootstrap allowance — that is an acceptable outcome and does not need to be exact. Nothing else about intake, the daily cap, or per-feed limits changes.

**Key interfaces:**
- The new-Source bootstrap allowance inside `FeedSyncService.syncAll(context:)` — must tolerate two Sources resolving to the same key rather than trapping.
- `Article.sourceName` — note that an Article identifies its Source by **name**, which is why "has this Source cached anything?" is a name-level question. Re-keying the allowance by URL alone does not work: with two same-named Sources you cannot tell which one owns the cached articles.

**Acceptance criteria:**
- [ ] A sync with two enabled Sources sharing a name and no cached articles completes and returns an article count instead of trapping.
- [ ] The same sync, run again once articles exist under that name, still completes.
- [ ] A Source that genuinely has nothing cached still receives its bootstrap allowance outside the daily cap — the behaviour this code exists for is preserved.
- [ ] The daily intake cap is still enforced for Sources that already have cached articles.
- [ ] Covered by a test that builds the colliding state over an in-memory store. The URLs need not be reachable; the defect does not depend on any feed responding.
- [ ] The existing feed-sync and RSS parser suites still pass.

**Out of scope:**
- Changing how `PackSourceOffer` matches suggestions. Matching by URL rather than name is deliberate and documented — it is what stops a Pack re-offering a Source the reader already has under a different name.
- Making Source names unique, or preventing a second Source from taking an existing name.
- Reworking how an `Article` references its Source. Linking by name rather than by identity is the deeper issue underneath this one, and it is a much larger change that should not ride along here.
- The unrelated duplicate-key defect in Pack installation, tracked as #22.
